#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# MySQL with auto-completion.
alias mysql="mysql -u root -p"
alias pdfconcat='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
